version: '3'
services:
    composer:
        image: library/composer:latest
        container_name: composer
        volumes:
            - .:/app
        working_dir: /app
    npm:
        image: node:13.7
        container_name: npm
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: npm
